export default {
    TRADE_IN_EXISTS_CHOOSER: 0,
    TRADE_IN_CAR_DEFINITION: 1,
    TRADE_IN_CONFIRM_CAR: 2,

    PAYMENT_METHOD_CHOOSER: 3,
    PAYMENT_FINANCING_DETAILS: 4,

    INSURANCE_TYPE_CHOOSER: 5,
    INSURANCE_INFORMATION_DEFINITION: 6,
    INSURANCE_ALTERNATIVE_CHOOSER: 7,

    CUSTOMER_INFORMATION_INITIAL: 8,
    CUSTOMER_INFORMATION_DETAILS: 9,

    DELIVERY_TYPE_CHOOSER: 10,

    FINAL_CONFIRMATION: 11,
};