enum StoreAction {
    UPDATE_NAMED_VALUE,

    INTERACT_SET_ALL_FOR_TYPE,
    INTERACT_UPDATE_SPECIFIC,

    PAYMENT_UPDATE_FINANCING_INFORMATION,

    TRADE_IN_CAR_UPDATE_HAS_TRADE_IN_CAR,
};

export default StoreAction;