enum EcomStep {
    TRADE_IN_EXISTS_CHOOSER,
    TRADE_IN_CAR_DEFINITION,
    TRADE_IN_CAR_CONDITION,
    TRADE_IN_CONFIRM_CAR,

    PAYMENT_METHOD_CHOOSER,
    PAYMENT_FINANCING_DETAILS,

    INSURANCE_INFORMATION_DEFINITION,
    INSURANCE_ALTERNATIVE_CHOOSER,

    CUSTOMER_INFORMATION_INITIAL,
    CUSTOMER_INFORMATION_DETAILS,

    DELIVERY_METHOD,

    FINAL_SUMMARY,
    FINAL_CONFIRMATION,
}

export default EcomStep;
