enum EcomStep {
    TRADE_IN_EXISTS_CHOOSER,
    TRADE_IN_CAR_DEFINITION,
    TRADE_IN_CONFIRM_CAR,

    PAYMENT_METHOD_CHOOSER,
    PAYMENT_FINANCING_DETAILS,

    INSURANCE_TYPE_CHOOSER,
    INSURANCE_INFORMATION_DEFINITION,
    INSURANCE_ALTERNATIVE_CHOOSER,

    CUSTOMER_INFORMATION_INITIAL,
    CUSTOMER_INFORMATION_DETAILS,

    FINAL_CONFIRMATION
};

export default EcomStep;