enum RequestType {
    GET_ORDER_OPTIONS,
    GET_VEHICLE_LOOKUP,
    GET_INSURANCE_OPTIONS,
    GET_ADDRESS_LOOKUP,
    GET_PAYMENT_LOOKUP,
    CREATE_ORDER,
    BANK_ID_AUTH,
    BANK_ID_COLLECT,
    BANK_ID_CANCEL,
    CREATE_CREDIT_ASSESSMENT_CASE,
    SIGN_CREDIT_ASSESSMENT_WITH_QR_CODE,
    SIGN_CREDIT_ASSESSMENT_WITH_SAME_DEVICE,
}

export default RequestType;
