enum StoreAction {
    UPDATE_NAMED_VALUE,

    INTERACT_SET_ALL_FROM_LIST,
    INTERACT_SET_ALL_FOR_TYPE,
    INTERACT_UPDATE_SPECIFIC,

    PAYMENT_UPDATE_FINANCING_INFORMATION,
}

export default StoreAction;
