enum StoreAction {
    UPDATE_NAMED_VALUE,
    UPDATE_MULTIPLE,

    INTERACT_SET_ALL_FOR_TYPE,
    INTERACT_UPDATE_SPECIFIC,

    PAYMENT_UPDATE_FINANCING_INFORMATION,
}

export default StoreAction;
